apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: kafka
    spec:
      containers:
        - args:
            - redpanda start
            - --kafka-addr PLAINTEXT://0.0.0.0:29092
            - --advertise-kafka-addr PLAINTEXT://kafka:29092
          image: docker.redpanda.com/vectorized/redpanda:v22.2.2
          name: kafka
          ports:
            - containerPort: 29092
              protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  type: ClusterIP
  ports:
    - name: "29092"
      port: 29092
      targetPort: 29092
  selector:
    io.kompose.service: kafka

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: worker-node
  name: worker-node
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker-node
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: worker-node
    spec:
      containers:
        - env:
            - name: ANCHOR_PRIVATE_KEY
              value: ""
            - name: AZURE_SENDER_ADRESS
              value: ""
            - name: COMMUNICATION_SERVICES_CONNECTION_STRING
              value: ""
            - name: DATABASE_URL
              value: ""
            - name: KAFKAJS_NO_PARTITIONER_WARNING
              value: ""
            - name: KAFKA_BROKER
              value: ""
          image: crapp.azurecr.io/worker-node:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:3001/health
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 10
          name: worker-node
          ports:
            - containerPort: 3001
              protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: worker-node
  name: worker-node
spec:
  type: LoadBalancer
  ports:
    - name: "3001"
      port: 80
      targetPort: 3001
  selector:
    io.kompose.service: worker-node
