version: "3.9"

services:
  worker-node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      KAFKA_BROKER: "kafka:29092"
    env_file:
      - .env
    depends_on:
      - kafka
  kafka:
    attach: false
    image: docker.redpanda.com/vectorized/redpanda:v22.2.2
    container_name: kafka
    ports:
      - "29092:29092"
    command:
      - redpanda start
      - --kafka-addr PLAINTEXT://0.0.0.0:29092
      - --advertise-kafka-addr PLAINTEXT://kafka:29092
